# Generated by Django 4.2.29 on 2026-03-20 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('hours_worked', models.FloatField(blank=True, help_text='Calculado automáticamente al hacer checkout', null=True)),
                ('photo_url', models.URLField(blank=True, help_text='URL pública de la foto en Google Drive', max_length=500)),
                ('lat_checkin', models.FloatField()),
                ('lon_checkin', models.FloatField()),
                ('lat_checkout', models.FloatField(blank=True, null=True)),
                ('lon_checkout', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], default='open', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'db_table': 'attendance_records',
                'ordering': ['-check_in'],
            },
        ),
    ]
