# Generated by Django 4.2.29 on 2026-03-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='hours_worked',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
