# Generated by Django 4.2.30 on 2026-06-22 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_systemgoogletoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='photo_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('uploaded', 'Subida'), ('failed', 'Fallida'), ('na', 'No aplica')], default='na', help_text='Estado de la subida de la foto a Google Drive', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
