# Generated by Django 4.2.29 on 2026-03-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(help_text='Descripción textual de la ubicación', max_length=255)),
                ('latitude', models.FloatField(help_text='Coordenada GPS — latitud')),
                ('longitude', models.FloatField(help_text='Coordenada GPS — longitud')),
                ('allowed_radius_m', models.FloatField(default=50.0, help_text='Radio permitido en metros para validar check-in')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'rooms',
            },
        ),
    ]
