# Generated by Django 4.2.29 on 2026-03-20 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='allowed_radius_m',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='room',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
